from magtogoek.odf_format import Odf

odf_dict = {
    "odf": {"file_specification": "MADCP_BOUEE2019_RIMOUSKI_553_VEL"},
    "cruise": {
        "country_institute_code": "CaIML",
        "cruise_number": "BOUEE2019",
        "organization": "DSOE",
        "chief_scientist": "Peter Galbraith",
        "start_date": "01-JAN-2019 00:00:00.00",
        "end_date": "31-DEC-2019 23:59:00.00",
        "platform": "BOUEE OCEANOGRAPHIQUE",
        "cruise_name": "Bouées océnographiques du golfe St-Laurent en 2019",
        "cruise_description": "",
    },
    "event": {
        "data_type": "MADCP",
        "event_number": "RIMOUSKI",
        "event_qualifier1": "553",
        "event_qualifier2": "VEL",
        "creation_date": "14-MAY-2020 15:21:11.53",
        "orig_creation_date": "17-NOV-1858 00:00:00.00",
        "start_date_time": "10-MAY-2019 19:30:00.00",
        "end_date_time": "17-NOV-2019 15:55:00.00",
        "initial_latitude": 48.6622,
        "initial_longitude": -68.5907,
        "end_latitude": 48.6713,
        "end_longitude": -68.5768,
        "min_depth": 10.47,
        "max_depth": 242.47,
        "sampling_interval": 900.0,
        "sounding": 335.0,
        "depth_off_bottom": 92.53,
        "event_comments": [
            "Station RIMOUSKI",
            "Fichier brut: RIMOUSKI_ADCP_VEL_2019.DAT RIMOUSKI_ADCP_ANC_2019.DAT",
            "Toutes les valeurs de courant obtenues avec moins de 90% de '4-beam solutions' sont jugées douteuses",
        ],
    },
    "buoy": {
        "name": "IML-4",
        "type": "MTE",
        "model": "Viking",
        "height": "4.5 m",
        "diameter": "2.1 m",
        "weight": "1000 kg",
        "description": "bouée noire (partie immergée) avec jaune.",
    },
    "plankton": {
        "water_volume": "",
        "volume_method": "",
        "lrg_plankton_removed": "",
        "collection_method": "",
        "mesh_size": "",
        "phase_of_daylight": "",
        "collector_dplmt_id": "",
        "collector_sample_id": "",
        "procedure": "",
        "preservation": "",
        "storage": "",
        "meters_sqd_flag": "",
        "plankton_comments": [],
    },
    "meteo": {
        "air_temperature": None,
        "atmospheric_pressure": None,
        "wind_speed": None,
        "wind_direction": None,
        "sea_state": None,
        "cloud_cover": None,
        "ice_thickness": None,
        "meteo_comments": [],
    },
    "instrument": {
        "inst_type": "",
        "model": "",
        "serial_number": "",
        "description": "",
    },
    "quality": {"quality_date": "", "quality_tests": [], "quality_comments": []},
    "record": {
        "num_calibration": 0,
        "num_swing": 0,
        "num_history": 1,
        "num_cycle": 549660,
        "num_param": 9,
    },
    "buoy_instrument": {
        "ADCP_01": {
            "name": "ADCP_01",
            "type": "Rowe Technologies Inc. (RTI)",
            "model": "ADCP/DVL",
            "serial_number": "553",
            "description": "firmware version 0.2.125-4",
            "inst_start_date_time": "10-MAY-2019 19:30:00.00",
            "inst_end_date_time": "17-NOV-2019 15:55:00.00",
            "buoy_instrument_comments": [
                "",
                "CONFIGURATION_01.Mode: DOWN",
                "CONFIGURATION_01.Pings_par_Ensemble: 100.0",
                "CONFIGURATION_01.Intervalle_des_pings_s: 0.6",
                "CONFIGURATION_01.Duree_dun_ensemble_s: 60.0",
                "CONFIGURATION_01.Profondeur_de_lADCP_m: 1.0",
                "CONFIGURATION_01.Distance_ADCP_au_centre_du_premier_bin_m: 9.75",
                "CONFIGURATION_01.Taille_dun_bin_m: 8.0",
                "CONFIGURATION_01.Nombre_de_bins: 30",
                "CONFIGURATION_01.Blank_m: ",
                "CONFIGURATION_01.Lag_length_m: ",
                "CONFIGURATION_01.Transmit_Pulse_Length_m: ",
                "CONFIGURATION_01.Declinaison_magnetique_deg: 17.36 W",
                "CONFIGURATION_01.Commentaire: .",
            ],
            "sensors": [
                "SENSEUR_TEMPERATURE_01.CODE: TE90_01",
                "SENSEUR_TEMPERATURE_01.Nom: temperature",
                "SENSEUR_TEMPERATURE_01.Marque: Rowe Technologies Inc. (RTI)",
                "SENSEUR_TEMPERATURE_01.Modele: ADCP/DVL",
                "SENSEUR_TEMPERATURE_01.Numero_de_serie: 553",
                "SENSEUR_TEMPERATURE_01.Description: ",
                "SENSEUR_TEMPERATURE_01.Date_debut: 10-MAY-2019 19:30:00.00",
                "SENSEUR_TEMPERATURE_01.Date_fin: 17-NOV-2019 15:55:00.00",
                "SENSEUR_TEMPERATURE_01.Profondeur_m: 1.0",
                "SENSEUR_TEMPERATURE_01.Commentaire: Modele et numero de serie identique a ceux de l\x92instrument.",
                "SENSEUR_TEMPERATURE_01.ETALONNAGE_01.Date: 01-APR-2019 00:00:00.00",
                "SENSEUR_TEMPERATURE_01.ETALONNAGE_01.Nombre_de_coefficients: S/O",
                "SENSEUR_TEMPERATURE_01.ETALONNAGE_01.Coefficients: S/O",
                "SENSEUR_TEMPERATURE_01.ETALONNAGE_01.Equation_detalonnage: S/O",
                "SENSEUR_TEMPERATURE_01.ETALONNAGE_01.Unites_detalonnage: degrés Celsius (ITS90)",
                "SENSEUR_TEMPERATURE_01.ETALONNAGE_01.Unites_darchivage: degrés Celsius (ITS90)",
                "SENSEUR_TEMPERATURE_01.ETALONNAGE_01.Facteur_de_conversion: 1",
                "SENSEUR_TEMPERATURE_01.ETALONNAGE_01.Commentaire: Date approximative. Verification du senseur.",
                "SENSEUR_COMPAS_01.CODE: HEAD_01",
                "SENSEUR_COMPAS_01.Nom: compas",
                "SENSEUR_COMPAS_01.Marque: Rowe Technologies Inc. (RTI)",
                "SENSEUR_COMPAS_01.Modele: ADCP/DVL",
                "SENSEUR_COMPAS_01.Numero_de_serie: 553",
                "SENSEUR_COMPAS_01.Description: ",
                "SENSEUR_COMPAS_01.Date_debut: 10-MAY-2019 19:30:00.00",
                "SENSEUR_COMPAS_01.Date_fin: 17-NOV-2019 15:55:00.00",
                "SENSEUR_COMPAS_01.Profondeur_m: 0.0",
                "SENSEUR_COMPAS_01.Commentaire: modele et numero de serie identique a ceux de l\x92instrument.",
                "SENSEUR_COMPAS_01.ETALONNAGE_01.Date: 01-APR-2019 00:00:00.00",
                "SENSEUR_COMPAS_01.ETALONNAGE_01.Nombre_de_coefficients: S/O",
                "SENSEUR_COMPAS_01.ETALONNAGE_01.Coefficients: S/O",
                "SENSEUR_COMPAS_01.ETALONNAGE_01.Equation_detalonnage: S/O",
                "SENSEUR_COMPAS_01.ETALONNAGE_01.Unites_detalonnage: degrés vrai",
                "SENSEUR_COMPAS_01.ETALONNAGE_01.Unites_darchivage: degrés vrai",
                "SENSEUR_COMPAS_01.ETALONNAGE_01.Facteur_de_conversion: 1",
                "SENSEUR_COMPAS_01.ETALONNAGE_01.Commentaire: Date approximative. Verification assiste par l`ADCP.",
                "SENSEUR_INCLINOMETRE_01.CODE: ROLL_01",
                "SENSEUR_INCLINOMETRE_01.Nom: inclinaison",
                "SENSEUR_INCLINOMETRE_01.Marque: Rowe Technologies Inc. (RTI)",
                "SENSEUR_INCLINOMETRE_01.Modele: ADCP/DVL",
                "SENSEUR_INCLINOMETRE_01.Numero_de_serie: 553",
                "SENSEUR_INCLINOMETRE_01.Description: mesure pitch et roll.",
                "SENSEUR_INCLINOMETRE_01.Date_debut: 10-MAY-2019 19:30:00.00",
                "SENSEUR_INCLINOMETRE_01.Date_fin: 17-NOV-2019 15:55:00.00",
                "SENSEUR_INCLINOMETRE_01.Profondeur_m: 1.0",
                "SENSEUR_INCLINOMETRE_01.Commentaire: modele et numero de serie identique a ceux de l\x92instrument.",
                "SENSEUR_INCLINOMETRE_01.ETALONNAGE_01.Date: 01-APR-2019 00:00:00.00",
                "SENSEUR_INCLINOMETRE_01.ETALONNAGE_01.Nombre_de_coefficients: S/O",
                "SENSEUR_INCLINOMETRE_01.ETALONNAGE_01.Coefficients: S/O",
                "SENSEUR_INCLINOMETRE_01.ETALONNAGE_01.Equation_detalonnage: S/O",
                "SENSEUR_INCLINOMETRE_01.ETALONNAGE_01.Unites_detalonnage: degrés",
                "SENSEUR_INCLINOMETRE_01.ETALONNAGE_01.Unites_darchivage: degrés",
                "SENSEUR_INCLINOMETRE_01.ETALONNAGE_01.Facteur_de_conversion: 1",
                "SENSEUR_INCLINOMETRE_01.ETALONNAGE_01.Commentaire: Date approximative. Verification assiste par l`ADCP.",
                "SENSEUR_PRESSION_01.CODE: DEPH_01",
            ],
        }
    },
    "general_cal": {},
    "polynomial_cal": {},
    "compass_cal": {},
    "history": {
        "history_0": {
            "creation_date": "14-MAY-2020 15:21:08.91",
            "process": "Conversion from BOUEE to ODF",
        }
    },
    "parameter": {
        "SYTM_01": {
            "type": "SYTM",
            "name": "Time Format DD-MMM-YYYY HH:MM:SS.ss",
            "units": "GMT",
            "code": "SYTM_01",
            "null_value": "17-NOV-1858 00:00:00.00",
            "print_field_width": 23,
            "print_decimal_places": 0,
            "angle_of_section": 0.0,
            "magnetic_variation": 0.0,
            "depth": 0.0,
            "minimum_value": "10-MAY-2019 19:30:00.00",
            "maximum_value": "17-NOV-2019 15:46:05.00",
            "number_valid": 549660,
            "number_null": 0,
        },
        "DEPH_01": {
            "type": "DOUB",
            "name": "Sensor Depth below Sea Surface",
            "units": "metres",
            "code": "DEPH_01",
            "null_value": -99.0,
            "print_field_width": 10,
            "print_decimal_places": 3,
            "angle_of_section": 0.0,
            "magnetic_variation": 0.0,
            "depth": 0.0,
            "minimum_value": 10.47,
            "maximum_value": 242.47,
            "number_valid": 549660,
            "number_null": 0,
        },
        "EWCT_01": {
            "type": "DOUB",
            "name": "East (true) Component of Current",
            "units": "m/s",
            "code": "EWCT_01",
            "null_value": 999.9999,
            "print_field_width": 10,
            "print_decimal_places": 4,
            "angle_of_section": 0.0,
            "magnetic_variation": -17.36,
            "depth": 0.0,
            "minimum_value": -0.5108,
            "maximum_value": 0.8545,
            "number_valid": 549643,
            "number_null": 17,
        },
        "QQQQ_01": {
            "type": "DOUB",
            "name": "Quality flag: East (true) Component of Current",
            "units": "none",
            "code": "QQQQ_01",
            "null_value": 9,
            "print_field_width": 1,
            "print_decimal_places": 0,
            "angle_of_section": 0.0,
            "magnetic_variation": 0.0,
            "depth": 0.0,
            "minimum_value": 0,
            "maximum_value": 3,
            "number_valid": 549660,
            "number_null": 0,
        },
        "NSCT_01": {
            "type": "DOUB",
            "name": "North (true) Component of Current",
            "units": "m/s",
            "code": "NSCT_01",
            "null_value": 999.9999,
            "print_field_width": 10,
            "print_decimal_places": 4,
            "angle_of_section": 0.0,
            "magnetic_variation": -17.36,
            "depth": 0.0,
            "minimum_value": -0.6574,
            "maximum_value": 0.9837,
            "number_valid": 549643,
            "number_null": 17,
        },
        "QQQQ_02": {
            "type": "DOUB",
            "name": "Quality flag: North (true) Component of Current",
            "units": "none",
            "code": "QQQQ_02",
            "null_value": 9,
            "print_field_width": 1,
            "print_decimal_places": 0,
            "angle_of_section": 0.0,
            "magnetic_variation": 0.0,
            "depth": 0.0,
            "minimum_value": 0,
            "maximum_value": 3,
            "number_valid": 549660,
            "number_null": 0,
        },
        "VCSP_01": {
            "type": "DOUB",
            "name": "Vertical Current Speed (positive up)",
            "units": "m/s",
            "code": "VCSP_01",
            "null_value": 999.9999,
            "print_field_width": 10,
            "print_decimal_places": 4,
            "angle_of_section": 0.0,
            "magnetic_variation": 0.0,
            "depth": 0.0,
            "minimum_value": -0.1936,
            "maximum_value": 0.191,
            "number_valid": 549643,
            "number_null": 17,
        },
        "QQQQ_03": {
            "type": "DOUB",
            "name": "Quality flag: Vertical Current Speed (positive up)",
            "units": "none",
            "code": "QQQQ_03",
            "null_value": 9,
            "print_field_width": 1,
            "print_decimal_places": 0,
            "angle_of_section": 0.0,
            "magnetic_variation": 0.0,
            "depth": 0.0,
            "minimum_value": 0,
            "maximum_value": 3,
            "number_valid": 549660,
            "number_null": 0,
        },
        "ERRV_01": {
            "type": "DOUB",
            "name": "Error Velocity (ADCP)",
            "units": "m/s",
            "code": "ERRV_01",
            "null_value": 999.9999,
            "print_field_width": 10,
            "print_decimal_places": 4,
            "angle_of_section": 0.0,
            "magnetic_variation": 0.0,
            "depth": 0.0,
            "minimum_value": -1.0612,
            "maximum_value": 1.0608,
            "number_valid": 538311,
            "number_null": 11349,
        },
    },
}

test_files = "files/MADCP_BOUEE2019_RIMOUSKI_553_VEL.ODF"
odf = Odf().read(test_files)
data = odf.__dict__.pop("data")


def test_read():
    assert odf.__dict__ == odf_dict
