#+Author: jerome.guay@protonmail.com
#+TITLE: Notes on Magtogoek

* New BODC parameters:

*** ADCP Inconsistency
 - ADCP vs acoustic doppler current profiler(ADCP).
 - (lower adcp/moored adcp/shipborne) not used for (by ADCP bottom tracking).
 - (Eulerian measurement) missing for (relative to moving platform).

** ADCP Lagrangian velocities for drift()
 - (LRZALA01 ?) "Upward velocity of water current (Lagrangian measurement) in the water body by tracked drifting buoy"

** ADCP beam velocity
 - Radial velocity (away from) of water current in the water body by moored acoustic doppler current profiler (ADCP) beam 1
 - Radial velocity (away from) of water current in the water body by moored acoustic doppler current profiler (ADCP) beam 2
 - Radial velocity (away from) of water current in the water body by moored acoustic doppler current profiler (ADCP) beam 3
 - Radial velocity (away from) of water current in the water body by moored acoustic doppler current profiler (ADCP) beam 4
** ADCP beam velocity raw (maybe) ?
- add 'relative to moving platform'

** ADCP beam bt velocity
 - Radial velocity (away from) of water current in the water body by ADCP bottom tracking beam 1
 - Radial velocity (away from) of water current in the water body by ADCP bottom tracking beam 2
 - Radial velocity (away from) of water current in the water body by ADCP bottom tracking beam 3
 - Radial velocity (away from) of water current in the water body by ADCP bottom tracking beam 4

** ADCP xyz velocity
 - Velocity along x-axis of water current in the water body by acoustic doppler current profiler (ADCP)
 - Velocity along y-axis of water current in the water body by acoustic doppler current profiler (ADCP)
 - Upward current velocity of water current in the water body by acoustic doppler current profiler (ADCP)
** ADCP xyz velocity raw
 - add 'relative to moving platform'

** ADCP xyz bt velocity
 - Velocity along x-axis of water current in the water body by ADCP bottom tracking
 - Velocity along y-axis of water current in the water body by ADCP bottom tracking
 - Upward current velocity of water current in the water body by ADCP bottom tracking

** ADCP enu velocity raw
 - Upward velocity of water current relative to moving platform in the water body by shipborne acoustic doppler current profiler (ADCP)

** ADCP enu bt velocity
 - (LRZABT01) Upward velocity of water current (Eulerian measurement) in the water body by ADCP bottom tracking
 - (LERRBT01) Upward velocity of water current (Eulerian measurement) in the water body by ADCP bottom tracking

* Issues.
** Motion Correction in Adcp adcp/quality_control.py and load_navigation in navigation.
   A fix has been added in vicking_dat branche.
   The load_navigation can return None if lon, lat are missing from the files which will crash in quality_control.py.
   Furthermore, the motion_correction function in quality_control.py needs to have longitude (and latitude) data to check for finite values.
   The code can crash there also since there is no if or else.

  
* Functionality
** Tool to merge dataset and recompute metadata / format existing data.

* Commands to add.
** Navigation command.
*** Add Navigation loadable from csv file maybe ?
   -n nc_filename
   -o output netcdf4 file name
   -l longitude_var_name latitude_var_name (2 args)
   -t time_dims_name
   -w length of the averaging window

** Rotation command.

* Improvements
** ADCP QUALITY CONTROL
*** Change PG good test for beam coord. each should be greater than 25% sum > 100.
*** ADCP figures
plt.show(block=False)
** ODF
*** time are printed with singles quotes
*** move odf specific config in .ini to separate header
** Add BODC name de compute nav variables (lon, lat)
** Make a sci_tools.py module for the scientific function.
** Make DataClasses from loaded platform file.
** Put navigation and Odf in their own sub package.
** Imports configuration files.
   + P01, GF3, CF, etc.
   + Maybe put this in the ConfigFiles.
   + Set the default configuration for the ConfigFiles.
   + Set default Value for the quick processing.

** Platform files.
   + Make use of a single platform file that can be modify by the user.

** VERSION:
    Put the version.py info in the __ini__.py ?
     
* Missing
** adcp
   + rotate command: mtgk rotate NETCDF_FILES ANGLE -o [output_files]
 
* Others
** Review documentations
