#+Author: jerome.guay@protonmail.com
#+TITLE: Notes on Magtogoek

* New BODC parameters:

** ADCP code for raw velocity (relative to moving platform)

*** ADCP Inconsistency
 - moored accoustic doppler current profile (ADCP) beam X exist but not for shipborne or lowered.
 - ADCP vs acoustic doppler current profiler(ADCP).
 - (lower adcp/moored adcp/shipborne) OR (by ADCP bottom tracking).
 - (Eulerian measurement) missing for (relative to moving platform). LCN... C -> eurelien ? R-> relative

** ADCP beam velocity S for ship, LW for lowered.

 - (LCRRAP01) Radial velocity (away from) of water current (Eulerian measurement) in the water body by moored acoustic doppler current profiler (ADCP) beam 1
 - (LCRRAP02) Radial velocity (away from) of water current (Eulerian measurement) in the water body by moored acoustic doppler current profiler (ADCP) beam 2
 - (LCRRAP03) Radial velocity (away from) of water current (Eulerian measurement) in the water body by moored acoustic doppler current profiler (ADCP) beam 3
 - (LCRRAP04) Radial velocity (away from) of water current (Eulerian measurement) in the water body by moored acoustic doppler current profiler (ADCP) beam 4

** ADCP beam bt velocity
 - (LCRRBT01) Radial velocity (away from) of water current (Eulerian measurement) in the water body by ADCP bottom tracking beam 1
 - (LCRRBT02) Radial velocity (away from) of water current (Eulerian measurement) in the water body by ADCP bottom tracking beam 2
 - (LCRRBT03) Radial velocity (away from) of water current (Eulerian measurement) in the water body by ADCP bottom tracking beam 3
 - (LCRRBT04) Radial velocity (away from) of water current (Eulerian measurement) in the water body by ADCP bottom tracking beam 4

** ADCP xyz velocity (shipeborne S, lowered LW)
 - (LCXAAP01) Velocity along x-axis of water current (Eulerian measurement) in the water body by moored acoustic doppler current profiler (ADCP)
 - (LCYAAP01) Velocity along y-axis of water current (Eulerian measurement) in the water body by moored acoustic doppler current profiler (ADCP)
 - (LCZAAP01) Upward current velocity of water current (Eulerian measurement) in the water body by moored acoustic doppler current profiler (ADCP)
 - (LERRAP01) Upward current velocity of water current (Eulerian measurement) in the water body by moored acoustic doppler current profiler (ADCP)

** ADCP xyz bt velocity
 - (LCXABT01) Velocity along x-axis of water current (Eulerian measurement) in the water body by ADCP bottom tracking
 - (LCYABT01) Velocity along y-axis of water current (Eulerian measurement) in the water body by ADCP bottom tracking
 - (LCZABT01) Upward current velocity of water current (Eulerian measurement) in the water body by ADCP bottom tracking
 - (LERRBT01) Current velocity error the water body by ADCP bottom tracking

** ADCP enu bt velocity
 - (LRZABT01) Upward velocity of water current (Eulerian measurement) in the water body by ADCP bottom tracking
 - (LERRBT01) Upward velocity of water current (Eulerian measurement) in the water body by ADCP bottom tracking

* Issues.
** Motion Correction in Adcp adcp/quality_control.py and load_navigation in navigation.
   A fix has been added in vicking_dat branche.
   The load_navigation can return None if lon, lat are missing from the files which will crash in quality_control.py.
   Furthermore, the motion_correction function in quality_control.py needs to have longitude (and latitude) data to check for finite values.
   The code can crash there also since there is no if or else.

  
* Functionality
** Tool to merge dataset and recompute metadata / format existing data.

* Commands to add.
** Navigation command.
*** Add Navigation loadable from csv file maybe ?
   -n nc_filename
   -o output netcdf4 file name
   -l longitude_var_name latitude_var_name (2 args)
   -t time_dims_name
   -w length of the averaging window

** Rotation command.

* Improvements
** ADCP QUALITY CONTROL
*** Change PG good test for beam coord. each should be greater than 25% sum > 100.
*** ADCP figures
plt.show(block=False)
** ODF
*** time are printed with singles quotes
*** move odf specific config in .ini to separate header
** Add BODC name de compute nav variables (lon, lat)
** Make a sci_tools.py module for the scientific function.
** Make DataClasses from loaded platform file.
** Put navigation and Odf in their own sub package.
** Imports configuration files.
   + P01, GF3, CF, etc.
   + Maybe put this in the ConfigFiles.
   + Set the default configuration for the ConfigFiles.
   + Set default Value for the quick processing.

** Platform files.
   + Make use of a single platform file that can be modify by the user.

** VERSION:
    Put the version.py info in the __ini__.py ?
     
* Missing
** adcp
   + rotate command: mtgk rotate NETCDF_FILES ANGLE -o [output_files]
 
* Others
** Review documentations
